# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TouchPainter' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  pod 'PLCrashReporter', '~> 1.2.0'

  target 'TouchPainterTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TouchPainterUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
